---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: ${aws-controller-config}
spec:
  metadata:
    annotations:
      eks.amazonaws.com/role-arn: ${iam-role-arn}
  serviceAccountName: ${aws-provider-service-account}
  podSecurityContext:
    fsGroup: 2000
  args:
    - --debug
