kubecostToken: ${kubecostToken}

global:
  grafana:
    enabled: false
    proxy: false
    
serviceAccount:
  create: true
  name: ${service-account}
  annotations:
    eks.amazonaws.com/role-arn: ${iam-role-arn}

kubecostProductConfigs:
  projectID: ${projectID}
  awsSpotDataRegion: ${awsSpotDataRegion}
  awsSpotDataBucket: ${awsSpotDataBucket}
  spotLabel: eks.amazonaws.com/capacityType
  spotLabelValue: SPOT
  athenaProjectID: ${athenaProjectID}
  athenaBucketName: ${athenaBucketName}
  athenaRegion: ${athenaRegion}
  athenaDatabase: ${athenaDatabase}
  athenaTable: ${athenaTable}
