repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
        exclude: '[\w\-\/]+/templates/'
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.53.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-exiting-file=true
      - id: terraform_validate
      - id: terraform_tflint
default_stages: [commit, push]
