agones:
  featureGates: ""
  crds:
    cleanupOnDelete: true
  ping:
    http:
      serviceType: LoadBalancer
    udp:
      expose: ${expose_udp}
  image:
    registry: us-docker.pkg.dev/agones-images/release
    controller:
      pullPolicy: IfNotPresent
    sdk:
      alwaysPull: false
gameservers:
  namespaces: ["default"]
  minPort: ${gameserver_minport}
  maxPort: ${gameserver_maxport}
  podPreserveUnknownFields: false
