serviceAccounts:
  server:
    create: true

server:
  retention: 1h
  remoteWrite:
    - queue_config:
        max_samples_per_send: 1000
        max_shards: 200
        capacity: 2500

  resources:
    # limits:
    #   cpu: 1000m
    #   memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi

  verticalAutoscaler:
    enabled: true
    updateMode: "Auto"
    containerPolicies:
      - containerName: "prometheus-server"
        minAllowed:
          cpu: 500m
          memory: 512Mi
        maxAllowed:
          cpu: 1000m
          memory: 2048Mi
        # controlledResources: ["cpu", "memory"]

  global:
    scrape_interval: 15s

  nodeSelector:
    kubernetes.io/os: ${operating_system}

alertmanager:
  nodeSelector:
    kubernetes.io/os: ${operating_system}

kube-state-metrics:
  nodeSelector:
    kubernetes.io/os: ${operating_system}

nodeExporter:
  nodeSelector:
    kubernetes.io/os: ${operating_system}

pushgateway:
  nodeSelector:
    kubernetes.io/os: ${operating_system}

nodeSelector:
  kubernetes.io/os: ${operating_system}
