apiVersion: v1
kind: Pod
metadata:
  name: fsx-taxi-exec
  namespace: emr-data-team-a
spec:
  volumes:
    - name: spark-local-dir-ny-taxi
      persistentVolumeClaim:
        claimName: fsx-static-pvc

  nodeSelector:
    NodeGroupType: spark
#    topology.kubernetes.io/zone: us-west-2a
#    beta.kubernetes.io/instance-type: r5d.large

  containers:
    - name: spark-kubernetes-executor # Don't change this name. EMR on EKS looking for this name
      volumeMounts:
        - name: spark-local-dir-ny-taxi
          mountPath: /static              # mountPath name can be anything but this should match with Driver template as well
          readOnly: false
