apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: [${azs}]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64", "amd64"]
  limits:
    resources:
      cpu: 1000
  provider:
    subnetSelector:
      Name: "${eks-vpc_name}-private*"
    securityGroupSelector:
      karpenter.sh/discovery/${eks-cluster-id}: '${eks-cluster-id}'
  labels:
    type: karpenter
    provisioner: default
  taints:
    - key: default
      value: 'true'
      effect: NoSchedule
  ttlSecondsAfterEmpty: 120
