apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: [${azs}]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
  limits:
    resources:
      cpu: 1000
  provider:
    amiFamily: Bottlerocket
    instanceProfile: ${iam-instance-profile-id}
    subnetSelector:
      Name: "${eks-vpc_name}-private*"
    securityGroupSelector:
      karpenter.sh/discovery/${eks-cluster-id}: '${eks-cluster-id}'
  labels:
    type: karpenter
    provisioner: default
  ttlSecondsAfterEmpty: 120
  ttlSecondsUntilExpired: 86400 # 1 day = 86400 ; 30 days = 2592000
