apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: {{ .Values.namespace }}
      server: {{ .Values.destination.server | quote }}
  sourceRepos:
    {{- range .Values.sourceRepos }}
    - {{ . | quote }}
    {{- end }}
