## Create default rules for monitoring the cluster
## Disable rules for unreachable components
##
defaultRules:
  create: true
  rules:
    etcd: false
    kubeScheduler: false

## Disable component scraping for the kube controller manager, etcd, and kube-scheduler
## These components are not reachable on EKS
##
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false

## additional configuration options available here: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
