## Create default rules for monitoring the cluster
##
defaultRules:
  create: true
  rules:
    etcd: false
    kubeScheduler: false

##
global:
  rbac:
    create: true


## Component scraping the kube controller manager
##
kubeControllerManager:
  enabled: false


## Component scraping etcd
##
kubeEtcd:
  enabled: false


## Component scraping kube scheduler
##
kubeScheduler:
  enabled: false

  ## Prometheus-operator image
  ##
  image:
    repository: quay.io/prometheus-operator/prometheus-operator
    tag: v0.57.0
    sha: ""
    pullPolicy: IfNotPresent

  ## Prometheus-config-reloader
  ##
  prometheusConfigReloader:
    # image to use for config and rule reloading
    image:
      repository: quay.io/prometheus-operator/prometheus-config-reloader
      tag: v0.57.0
      sha: ""

  ## Thanos side-car image when configured
  ##
  thanosImage:
    repository: quay.io/thanos/thanos
    tag: v0.25.2
    sha: ""

## Deploy a Prometheus instance
##
prometheus:
    ## Image of Prometheus.
    ##
    image:
      repository: quay.io/prometheus/prometheus
      tag: v2.36.1
      sha: ""
