apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: adot
subjects:
  - kind: ServiceAccount
    name: adot-collector
  - kind: ServiceAccount
    name: amp-ingest
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
