apiVersion: v1
kind: Pod
metadata:
  name: ny-taxi-exec
  namespace: emr-team-a
spec:
  volumes:
    - name: metrics-files-volume
      emptyDir: {}
    - name: spark-local-dir-ny-taxi
      hostPath:
        path: /local1/ny-taxi
        type: DirectoryOrCreate

  nodeSelector:
    "NodeGroupType": "spark"

  containers:
    - name: spark-kubernetes-executor # Don't change this name. EMR on EKS looking for this name
      volumeMounts:
        - name: spark-local-dir-ny-taxi
          mountPath: /local1/ny-taxi
        - name: metrics-files-volume
          mountPath: /var/metrics/data
#  initContainers:
#    - name: spark-init-container-executor  # Don't change this name. EMR on EKS looking for this name
#      image: public.ecr.aws/y4g4v0z7/busybox
#      volumeMounts:
#        - name: spark-local-dir-ny-taxi
#          mountPath: /local1/ny-taxi
#      command: ["sh", "-c", "chmod -R 777 /local1"] # This is only for PoC. Will update with min permissions
