name: e2e-test-cleanup

on:
  workflow_dispatch:

jobs:
    deploy:
      name: Run e2e test cleanup
      runs-on: ubuntu-latest

      # These permissions are needed to interact with GitHub's OIDC Token endpoint.
      permissions:
        id-token: write
        contents: read

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Configure AWS credentials from Test account
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
            aws-region: us-west-2
            role-duration-seconds: 1800
            role-session-name: GithubActions-Session

        - name: Terraform Job
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.0.11

        - name: Terraform Init
          id: init
          run: terraform init
          working-directory: test/e2e/eks
          continue-on-error: false

        - name: Terraform Plan Destroy
          id: plan-destroy
          working-directory: test/e2e/eks
          run: terraform plan -destroy -no-color
          continue-on-error: false

        - name: Terraform Destroy
          id: destroy
          working-directory: test/e2e/eks
          run: terraform destroy -no-color -auto-approve
          continue-on-error: false
