name: e2e-parallel-full

on:
  workflow_dispatch:
    inputs:
      TFDestroy:
        description: 'Destroy TF Automatically (false/true) - Default: true'
        required: true
        default: 'true'
env:
  DEFAULT_DEPLOY_ORDER: 'module.vpc,module.vpc_endpoints,module.eks_blueprints'

concurrency: e2e-parallel-full

jobs:
  deploy:
    name: Run e2e test
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - example_path: examples/analytics/emr-on-eks
          - example_path: examples/analytics/spark-k8s-operator
          - example_path: examples/multi-tenancy-with-teams
          - example_path: examples/gitops/argocd
          - example_path: examples/crossplane
          - example_path: examples/aws-efs-csi-driver
          - example_path: examples/eks-cluster-with-new-vpc
          - example_path: examples/fully-private-eks-cluster
          - example_path: examples/game-tech/agones-game-controller
          - example_path: examples/ingress-controllers/nginx
          - example_path: examples/karpenter
          - example_path: examples/node-groups/managed-node-groups
          - example_path: examples/node-groups/self-managed-node-groups
          - example_path: examples/node-groups/windows-node-groups
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup backend
        # Un-comments remote backend for use in workflow
        run: sed -i "s/# //g" ${{ matrix.example_path }}/versions.tf

      - name: Setup Deployment Order
        id: setup-deployment-order
        run: |
          export MATRIX_DEPLOYMENT_ORDER=${{join(matrix.deployment_order,',') }}

          if [ -z "$MATRIX_DEPLOYMENT_ORDER" ]
          then
            DEPLOYMENT_ORDER=${{env.DEFAULT_DEPLOY_ORDER}}
          else
            DEPLOYMENT_ORDER=$MATRIX_DEPLOYMENT_ORDER
          fi
          echo "DEPLOYMENT_ORDER=$DEPLOYMENT_ORDER" >> $GITHUB_ENV

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-west-2
          role-duration-seconds: 3600
          role-session-name: GithubActions-Session

      - name: Terraform Job
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ matrix.example_path }}

      - name: Terraform Apply
        id: apply
        working-directory: deploy/e2e-test
        run: |
          IFS=',' read -r -a array <<< "${{ env.DEPLOYMENT_ORDER }}"
          for element in "${array[@]}"
          do
            terraform apply -target="$element" -no-color -input=false -auto-approve
          done
          terraform apply -no-color -input=false -auto-approve

      - name: Terraform Destroy
        if: github.event.inputs.TFDestroy == 'true' && (steps.apply.outcome == 'success' || steps.apply.outcome == 'failure')
        working-directory: deploy/e2e-test
        run: |
          reverse_array=$(echo ${{ env.DEPLOYMENT_ORDER }}  | awk -F, '{for (i=NF; i>0; --i) printf "%s%s", (i<NF ? "," : ""), $i; printf "\n"}')
          IFS=',' read -r -a array <<< "$reverse_array"
          for element in "${array[@]}"
          do
            terraform destroy -target="$element" -no-color -input=false -auto-approve
            sleep 45
          done
          terraform destroy -no-color -input=false -auto-approve

      - name: Fail if TF apply failed
        if: steps.apply.outcome == 'failure'
        run: |
          echo "Terraform Apply step failed...Please check the logs of the Terraform Apply step."
          echo "Failing the job to avoid false positives."
          exit 1
