name: terraform-docs
on:
  push:
    branches: [main]
  pull_request:
    types: [assigned, unassigned, opened, reopened, edited, synchronize]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'push'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: main

      - uses: actions/checkout@v2
        if: ${{ (github.event.pull_request.head.repo.full_name == github.repository) && (github.event_name == 'pull_request') }}
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v0.11.0
        if: github.event.pull_request.head.repo.full_name == github.repository
        with:
          find-dir: .
          output-file: README.md
          output-method: inject
          git-push: 'true'
          template: '<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->\n{{ .Content }}\n<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->'
