name: vpc-test

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Create VPC
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-west-2
          role-duration-seconds: 1800
          role-session-name: GithubActions-Session

      - name: Terraform Job
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check -recursive -list -no-color
        continue-on-error: false

      - name: Terraform Init
        id: init
        run: terraform init -backend-config backend.conf -reconfigure
        working-directory: deploy/e2e/vpc
        continue-on-error: false

      - name: Terraform Validate
        id: validate
        working-directory: deploy/e2e/vpc
        run: terraform validate -no-color
        continue-on-error: false

      - name: Terraform Plan
        id: plan
        working-directory: deploy/e2e/vpc
        run: terraform plan -var-file base.tfvars -no-color
        continue-on-error: false

      - name: Terraform Apply
        id: apply
        working-directory: deploy/e2e/vpc
        run: terraform apply -var-file base.tfvars -no-color -auto-approve
        continue-on-error: false
